#Site settings
url: "https://ronnylk.github.io/wells-variorum" # the base hostname & protocol for your site
baseurl: "/wells-variorum"

#Build settings
markdown: html
exclude: 
  - Gemfile
  - Gemfile.lock